### ISSUE TITLE
make Brand up arrow foldable

### ISSUE THREAD

**Issue by amreshk005** [amreshk005/shopTemplate#1]
<h3>Current state:</h3>
It is not working after clicking on it.

<h3>expected state:</h3>
Expected state, after clicking on it needs to fold.

<h6>Note:</h6>
Only use of vanilla js.
<hr>

![Screen Shot 2019-10-11 at 8 33 18 AM](https://user-images.githubusercontent.com/35935083/66621500-2072e080-ec02-11e9-9e72-85e50e335b1b.jpg)

**Comment by jyarali** [comment]
Hi, may I work on this?
